# Generated by Django 4.2.13 on 2026-05-31 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_review"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("in", "Stock In"),
                            ("out", "Stock Out"),
                            ("adjustment", "Adjustment"),
                            ("reservation", "Reservation"),
                            ("release", "Release"),
                        ],
                        max_length=20,
                        verbose_name="Movement Type",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                ("reason", models.TextField(blank=True, verbose_name="Reason")),
            ],
            options={
                "verbose_name": "Stock Movement",
                "verbose_name_plural": "Stock Movements",
                "ordering": ("-created_at",),
            },
        ),
        migrations.RemoveField(
            model_name="stocklevel",
            name="last_restocked",
        ),
        migrations.RemoveField(
            model_name="stocklevel",
            name="reorder_level",
        ),
        migrations.RemoveField(
            model_name="stocklevel",
            name="variant",
        ),
        migrations.AddField(
            model_name="stocklevel",
            name="product",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_levels",
                to="catalog.product",
                verbose_name="Product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stocklevel",
            name="reserved",
            field=models.PositiveIntegerField(default=0, verbose_name="Reserved"),
        ),
        migrations.DeleteModel(
            name="Stock",
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                to="inventory.stocklevel",
                verbose_name="Stock",
            ),
        ),
    ]
