# Generated by Django 5.2.13 on 2026-06-28 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "cdc",
                    models.CharField(
                        help_text="44-digit unique identifier (SIFEN)",
                        max_length=44,
                        unique=True,
                        verbose_name="CDC (Código de Control)",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("1", "Factura Electrónica"),
                            ("4", "Autofactura Electrónica"),
                            ("5", "Nota de Crédito Electrónica"),
                            ("6", "Nota de Débito Electrónica"),
                            ("7", "Nota de Remisión Electrónica"),
                        ],
                        default="1",
                        max_length=1,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "establecimiento",
                    models.CharField(
                        default="001", max_length=3, verbose_name="Establecimiento"
                    ),
                ),
                (
                    "punto_expedicion",
                    models.CharField(
                        default="001", max_length=3, verbose_name="Punto de Expedición"
                    ),
                ),
                (
                    "numero_documento",
                    models.PositiveIntegerField(verbose_name="Número de Documento"),
                ),
                (
                    "timbrado",
                    models.CharField(
                        help_text="Authorization number issued by DNIT",
                        max_length=8,
                        verbose_name="Timbrado",
                    ),
                ),
                (
                    "timbrado_fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Timbrado Vigente Desde"
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha y Hora de Emisión"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("issued", "Emitida"),
                            ("cancelled", "Anulada"),
                        ],
                        default="draft",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "receptor_tipo_doc",
                    models.CharField(
                        choices=[
                            ("1", "RUC"),
                            ("2", "Cédula de Identidad"),
                            ("3", "Pasaporte"),
                            ("4", "Innominado"),
                        ],
                        default="2",
                        max_length=1,
                        verbose_name="Tipo de Doc. Receptor",
                    ),
                ),
                (
                    "receptor_ruc",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="RUC / Cédula Receptor"
                    ),
                ),
                (
                    "receptor_nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre/Razón Social Receptor"
                    ),
                ),
                (
                    "receptor_direccion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dirección Receptor"
                    ),
                ),
                (
                    "receptor_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Receptor"
                    ),
                ),
                (
                    "condicion_venta",
                    models.CharField(
                        choices=[("1", "Contado"), ("2", "Crédito")],
                        default="1",
                        max_length=1,
                        verbose_name="Condición de Venta",
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        default="PYG", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "subtotal_gravado10",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Base imponible IVA 10% (precio sin IVA)",
                        max_digits=14,
                        verbose_name="Subtotal Gravado IVA 10%",
                    ),
                ),
                (
                    "subtotal_gravado5",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Base imponible IVA 5% (precio sin IVA)",
                        max_digits=14,
                        verbose_name="Subtotal Gravado IVA 5%",
                    ),
                ),
                (
                    "subtotal_exento",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=14,
                        verbose_name="Subtotal Exento",
                    ),
                ),
                (
                    "total_iva10",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=14,
                        verbose_name="Total IVA 10%",
                    ),
                ),
                (
                    "total_iva5",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=14,
                        verbose_name="Total IVA 5%",
                    ),
                ),
                (
                    "total_iva",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=14,
                        verbose_name="Total IVA",
                    ),
                ),
                (
                    "total_general",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=14,
                        verbose_name="Total General",
                    ),
                ),
                (
                    "kude_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="invoices/kude/%Y/%m/",
                        verbose_name="KuDE PDF",
                    ),
                ),
                (
                    "qr_url",
                    models.URLField(
                        blank=True,
                        help_text="URL for QR code pointing to e-Kuatia portal",
                        verbose_name="URL QR e-Kuatia",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="order.order",
                        verbose_name="Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura Electrónica",
                "verbose_name_plural": "Facturas Electrónicas",
                "ordering": ("-issued_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cantidad"
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=14,
                        verbose_name="Precio Unitario (con IVA)",
                    ),
                ),
                (
                    "tasa_iva",
                    models.CharField(
                        choices=[
                            ("10", "Gravado 10%"),
                            ("5", "Gravado 5%"),
                            ("0", "Exento"),
                        ],
                        default="10",
                        max_length=2,
                        verbose_name="Tasa IVA",
                    ),
                ),
                (
                    "subtotal_item",
                    models.DecimalField(
                        decimal_places=0, max_digits=14, verbose_name="Subtotal"
                    ),
                ),
                (
                    "iva_item",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=14,
                        verbose_name="IVA del ítem",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoicing.invoice",
                        verbose_name="Factura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Factura",
                "verbose_name_plural": "Ítems de Factura",
                "ordering": ("id",),
            },
        ),
    ]
