# Generated by Django 4.2.13 on 2026-05-31 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.category",
                        verbose_name="Parent category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "sku",
                    models.CharField(max_length=50, unique=True, verbose_name="SKU"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="products/", verbose_name="Image"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("XS", "Extra Small"),
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                            ("XXL", "XXL"),
                        ],
                        max_length=10,
                        verbose_name="Size",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Black, White, Navy Blue",
                        max_length=50,
                        verbose_name="Color",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 100% Cotton, Cotton Blend",
                        max_length=100,
                        verbose_name="Material",
                    ),
                ),
                (
                    "geek_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("anime", "Anime & Manga"),
                            ("gaming", "Gaming & Esports"),
                            ("movies", "Movies & TV"),
                            ("tech", "Tech & Science"),
                            ("meme", "Meme Culture"),
                        ],
                        max_length=50,
                        verbose_name="Geek Category",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Naruto Uzumaki",
                        max_length=100,
                        verbose_name="Character Name",
                    ),
                ),
                (
                    "franchise",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Naruto, Star Wars, The Witcher",
                        max_length=100,
                        verbose_name="Franchise",
                    ),
                ),
                (
                    "clothing_type",
                    models.CharField(
                        choices=[
                            ("tshirt", "T-Shirt"),
                            ("hoodie", "Hoodie"),
                            ("sweatshirt", "Sweatshirt"),
                            ("hat", "Hat/Cap"),
                            ("accessory", "Accessories"),
                        ],
                        max_length=50,
                        verbose_name="Clothing Type",
                    ),
                ),
                (
                    "gender_fit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unisex", "Unisex"),
                            ("mens", "Men's"),
                            ("womens", "Women's"),
                            ("kids", "Kids"),
                        ],
                        max_length=20,
                        verbose_name="Gender / Fit",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("XS", "Extra Small"),
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                            ("XXL", "XXL"),
                        ],
                        max_length=10,
                        verbose_name="Size",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Black, White, Navy Blue",
                        max_length=50,
                        verbose_name="Color",
                    ),
                ),
                (
                    "sku",
                    models.CharField(max_length=100, unique=True, verbose_name="SKU"),
                ),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Price Adjustment",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="variants/", verbose_name="Variant Image"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variant",
                "verbose_name_plural": "Product Variants",
                "indexes": [
                    models.Index(fields=["sku"], name="catalog_pro_sku_187601_idx"),
                    models.Index(
                        fields=["product", "is_active"],
                        name="catalog_pro_product_6c5ee9_idx",
                    ),
                ],
                "unique_together": {("product", "size", "color")},
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="catalog_pro_slug_2b1eb6_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="catalog_pro_sku_2c4c34_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active"], name="catalog_pro_is_acti_14fc6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["clothing_type"], name="catalog_pro_clothin_4d5f6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["geek_category"], name="catalog_pro_geek_ca_40a97b_idx"
            ),
        ),
    ]
