# Generated by Django 5.2.14 on 2026-06-01 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_review"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
