# Generated by Django 5.2.13 on 2026-07-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_delete_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="clothing_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tshirt", "T-Shirt"),
                    ("hoodie", "Hoodie"),
                    ("sweatshirt", "Sweatshirt"),
                    ("hat", "Hat/Cap"),
                    ("accessory", "Accessories"),
                ],
                default="",
                max_length=50,
                verbose_name="Clothing Type",
            ),
        ),
    ]
