# Generated by Django 5.2.13 on 2026-07-04 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order_confirmed", "Orden confirmada"),
                            ("order_shipped", "Orden enviada"),
                            ("order_delivered", "Orden entregada"),
                            ("order_cancelled", "Orden cancelada"),
                            ("payment_received", "Pago recibido"),
                            ("payment_failed", "Pago fallido"),
                            ("abandoned_cart", "Carrito abandonado"),
                            ("low_stock", "Stock bajo"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("message", models.TextField(verbose_name="Mensaje")),
                ("is_read", models.BooleanField(default=False, verbose_name="Leída")),
                (
                    "email_sent",
                    models.BooleanField(default=False, verbose_name="Email enviado"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="order.order",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ("-created_at",),
            },
        ),
    ]
